### ISSUE TITLE
Question about VsearchMergeLog

### ISSUE THREAD

**Issue by colinbrislawn** [bio-ontology-research-group/16SProcessing#1]
On lines [403-404](https://github.com/bio-ontology-research-group/16SProcessing/blob/main/16SProcessing.nf#L403-L404), is the `vsearch --fastq_mergepairs` function being called twice, or is Nextflow going to combine these two function in some way?

```nextflow
        vsearch_merge_out = VsearchMerge(read_pairs)
        VsearchMergeLog(read_pairs)
```

**Comment by coolmaksat** [comment]
Hi,
Thanks for reporting this. You are right, it will be called twice and needs to be fixed. @rund0wn please update.

**Comment by rund0wn** [comment]
Fixed and updated

**Comment by rund0wn** [comment]
Merged steps and separated outputs
